os: linux
arch:
 - amd64
 - ppc64le
language: perl
sudo: false
perl:
  #- "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
before_install:
  - "cpanm -n --installdeps --with-develop --with-recommends --with-suggests ."
